### ISSUE TITLE
Renderering bug on zoom level change

### ISSUE THREAD

**Issue by delewis13** [naomiaro/waveform-playlist#131] opened 2020-09-22 12:17 UTC
Hello,

First off thanks for this fantastic project, it's incredibly useful!

I've noticed that if you change the browser zoom level [tested on Chrome v85.0.4183.102], if you then click on the audio waveform anywhere, the rendered waveform becomes a solid block colour. 

This can be reproduced in your demos, e.g. http://naomiaro.github.io/waveform-playlist/minimal.html

Cheers :)

**Comment by QTimort** [comment] 2021-02-05 12:54
See https://github.com/naomiaro/waveform-playlist/issues/137#issuecomment-774013306

**Comment by Catsvilles** [comment] 2021-02-25 10:01
Had this issue too, link above helped (setting to 1)

**Comment by naomiaro** [comment] 2021-04-22 08:41
Woops, had thought this was a different zoom issue when closing originally

**Comment by p-himik** [comment] 2022-02-21 17:07
I'm afraid the above PR doesn't fix the issue.

The root cause of the behavior that I'm seeing is that `devicePixelRatio` becomes less than 1 on zoomed-out screens.
This leads to scale being set to 0 at this line: https://github.com/naomiaro/waveform-playlist/blob/f462a873c30e96c794d3b2167b100fc8d7f9cf3c/src/Track.js#L535

**Comment by naomiaro** [comment] 2022-02-21 18:17
Really? What kind of a device are you using? I can't recreate this on my retina screen or non retina screen.

**Comment by p-himik** [comment] 2022-02-21 18:23
A regular 2560x1440 display, Samsung LC32HG70QQUXEN. A colleague of mine was able to reproduce it on a Mac Mini 2018 with 27 inch 1920x1080 display. We're both using the latest version of Google Chrome.

Note that you can't just go to a web page with an example that uses `waveform-playlist` and _then_ zoom in. You have to load the page when it's already zoomed in for the scale to be re-computed based on the new `devicePixelRatio` value. Refreshing the page after you zoom in does reproduce the issue just fine though.

Another way to reproduce it is to use Chrome's Developer Tools - you can enable the device toolbar there (the one that's usually used to help with responsive design), add a custom device with "Device pixel ratio" set to e.g. 0.7, switch to that device, and refresh the page.

**Comment by p-himik** [comment] 2022-02-21 18:25
Do you remember the reason behind this commit? https://github.com/naomiaro/waveform-playlist/commit/42b01c3d7fe4ec59fbb26f06135080e74668f765
It doesn't have any details. I wonder what the issues are if the `floor` is not there.

**Comment by naomiaro** [comment] 2022-02-21 18:28
The rendering also becomes blocky if the devicePixelRatio isn't an integer (with zooming). Hmm ok I should just be able to set this to 1 if it's below 1, I'll see if that could work.

**Comment by naomiaro** [comment] 2022-02-21 18:30
I can recreate this now.

**Comment by p-himik** [comment] 2022-02-21 18:32
Would it make sense to make it an integer if it's >=1 (by using either `floor` or `round`) and to leave it as is if it's < 1?
I haven't tested it but just rounding it to 1 sounds like it could make it much worse when the zoom level is extreme.

**Comment by naomiaro** [comment] 2022-02-21 18:33
changing this to ceil seems to be fine.

**Comment by naomiaro** [comment] 2022-02-21 18:35
If it's < 1 then it won't render properly.

**Comment by naomiaro** [comment] 2022-02-21 18:37
I'll just make a quick patch changing this to ceil for now.

**Closed** 2022-02-21 18:39 UTC

**Comment by p-himik** [comment] 2022-02-21 20:07
Thanks for fixing it so quickly!

**Comment by naomiaro** [comment] 2022-02-21 20:31
Np, if you see any other issues please report!

**Comment by p-himik** [comment] 2022-02-21 20:33
Given my comment at https://github.com/naomiaro/waveform-playlist/commit/9843ee9672045cdd13272941988f81155a0798e0#commitcomment-67177014 I'll probably be creating PRs as well. :)
